from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model


class ChatCompletionNamedToolChoiceFunction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None):  # noqa: E501
        """ChatCompletionNamedToolChoiceFunction - a model defined in OpenAPI

        :param name: The name of this ChatCompletionNamedToolChoiceFunction.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'name': str
        }

        self.attribute_map = {
            'name': 'name'
        }

        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'ChatCompletionNamedToolChoiceFunction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatCompletionNamedToolChoice_function of this ChatCompletionNamedToolChoiceFunction.  # noqa: E501
        :rtype: ChatCompletionNamedToolChoiceFunction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ChatCompletionNamedToolChoiceFunction.

        The name of the function to call.  # noqa: E501

        :return: The name of this ChatCompletionNamedToolChoiceFunction.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ChatCompletionNamedToolChoiceFunction.

        The name of the function to call.  # noqa: E501

        :param name: The name of this ChatCompletionNamedToolChoiceFunction.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
