from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model


class ChatCompletionRequestMessageContentPartText(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, text=None):  # noqa: E501
        """ChatCompletionRequestMessageContentPartText - a model defined in OpenAPI

        :param type: The type of this ChatCompletionRequestMessageContentPartText.  # noqa: E501
        :type type: str
        :param text: The text of this ChatCompletionRequestMessageContentPartText.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'type': str,
            'text': str
        }

        self.attribute_map = {
            'type': 'type',
            'text': 'text'
        }

        self._type = type
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'ChatCompletionRequestMessageContentPartText':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatCompletionRequestMessageContentPartText of this ChatCompletionRequestMessageContentPartText.  # noqa: E501
        :rtype: ChatCompletionRequestMessageContentPartText
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ChatCompletionRequestMessageContentPartText.

        The type of the content part.  # noqa: E501

        :return: The type of this ChatCompletionRequestMessageContentPartText.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ChatCompletionRequestMessageContentPartText.

        The type of the content part.  # noqa: E501

        :param type: The type of this ChatCompletionRequestMessageContentPartText.
        :type type: str
        """
        allowed_values = ["text"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def text(self) -> str:
        """Gets the text of this ChatCompletionRequestMessageContentPartText.

        The text content.  # noqa: E501

        :return: The text of this ChatCompletionRequestMessageContentPartText.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this ChatCompletionRequestMessageContentPartText.

        The text content.  # noqa: E501

        :param text: The text of this ChatCompletionRequestMessageContentPartText.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text
