from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.array_of_content_parts_inner import \
    ArrayOfContentPartsInner  # noqa: E501
from timestep.api.openai.v1.models.base_model import Model


class CreateMessageRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """CreateMessageRequestContent - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CreateMessageRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateMessageRequest_content of this CreateMessageRequestContent.  # noqa: E501
        :rtype: CreateMessageRequestContent
        """
        return util.deserialize_model(dikt, cls)
