from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model


class CreateTranscriptionResponseJson(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text=None):  # noqa: E501
        """CreateTranscriptionResponseJson - a model defined in OpenAPI

        :param text: The text of this CreateTranscriptionResponseJson.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'text': str
        }

        self.attribute_map = {
            'text': 'text'
        }

        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'CreateTranscriptionResponseJson':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateTranscriptionResponseJson of this CreateTranscriptionResponseJson.  # noqa: E501
        :rtype: CreateTranscriptionResponseJson
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this CreateTranscriptionResponseJson.

        The transcribed text.  # noqa: E501

        :return: The text of this CreateTranscriptionResponseJson.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this CreateTranscriptionResponseJson.

        The transcribed text.  # noqa: E501

        :param text: The text of this CreateTranscriptionResponseJson.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text
