from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model
from timestep.api.openai.v1.models.create_assistant_request_tool_resources_code_interpreter import \
    CreateAssistantRequestToolResourcesCodeInterpreter  # noqa: E501
from timestep.api.openai.v1.models.create_thread_request_tool_resources_file_search import \
    CreateThreadRequestToolResourcesFileSearch  # noqa: E501


class CreateThreadRequestToolResources(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code_interpreter=None, file_search=None):  # noqa: E501
        """CreateThreadRequestToolResources - a model defined in OpenAPI

        :param code_interpreter: The code_interpreter of this CreateThreadRequestToolResources.  # noqa: E501
        :type code_interpreter: CreateAssistantRequestToolResourcesCodeInterpreter
        :param file_search: The file_search of this CreateThreadRequestToolResources.  # noqa: E501
        :type file_search: CreateThreadRequestToolResourcesFileSearch
        """
        self.openapi_types = {
            'code_interpreter': CreateAssistantRequestToolResourcesCodeInterpreter,
            'file_search': CreateThreadRequestToolResourcesFileSearch
        }

        self.attribute_map = {
            'code_interpreter': 'code_interpreter',
            'file_search': 'file_search'
        }

        self._code_interpreter = code_interpreter
        self._file_search = file_search

    @classmethod
    def from_dict(cls, dikt) -> 'CreateThreadRequestToolResources':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateThreadRequest_tool_resources of this CreateThreadRequestToolResources.  # noqa: E501
        :rtype: CreateThreadRequestToolResources
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code_interpreter(self) -> CreateAssistantRequestToolResourcesCodeInterpreter:
        """Gets the code_interpreter of this CreateThreadRequestToolResources.


        :return: The code_interpreter of this CreateThreadRequestToolResources.
        :rtype: CreateAssistantRequestToolResourcesCodeInterpreter
        """
        return self._code_interpreter

    @code_interpreter.setter
    def code_interpreter(self, code_interpreter: CreateAssistantRequestToolResourcesCodeInterpreter):
        """Sets the code_interpreter of this CreateThreadRequestToolResources.


        :param code_interpreter: The code_interpreter of this CreateThreadRequestToolResources.
        :type code_interpreter: CreateAssistantRequestToolResourcesCodeInterpreter
        """

        self._code_interpreter = code_interpreter

    @property
    def file_search(self) -> CreateThreadRequestToolResourcesFileSearch:
        """Gets the file_search of this CreateThreadRequestToolResources.


        :return: The file_search of this CreateThreadRequestToolResources.
        :rtype: CreateThreadRequestToolResourcesFileSearch
        """
        return self._file_search

    @file_search.setter
    def file_search(self, file_search: CreateThreadRequestToolResourcesFileSearch):
        """Sets the file_search of this CreateThreadRequestToolResources.


        :param file_search: The file_search of this CreateThreadRequestToolResources.
        :type file_search: CreateThreadRequestToolResourcesFileSearch
        """

        self._file_search = file_search
