from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model


class ModifyRunRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, metadata=None):  # noqa: E501
        """ModifyRunRequest - a model defined in OpenAPI

        :param metadata: The metadata of this ModifyRunRequest.  # noqa: E501
        :type metadata: object
        """
        self.openapi_types = {
            'metadata': object
        }

        self.attribute_map = {
            'metadata': 'metadata'
        }

        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'ModifyRunRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModifyRunRequest of this ModifyRunRequest.  # noqa: E501
        :rtype: ModifyRunRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> object:
        """Gets the metadata of this ModifyRunRequest.

        Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.   # noqa: E501

        :return: The metadata of this ModifyRunRequest.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this ModifyRunRequest.

        Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.   # noqa: E501

        :param metadata: The metadata of this ModifyRunRequest.
        :type metadata: object
        """

        self._metadata = metadata
