from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model
from timestep.api.openai.v1.models.run_object_required_action_submit_tool_outputs import \
    RunObjectRequiredActionSubmitToolOutputs  # noqa: E501


class RunObjectRequiredAction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, submit_tool_outputs=None):  # noqa: E501
        """RunObjectRequiredAction - a model defined in OpenAPI

        :param type: The type of this RunObjectRequiredAction.  # noqa: E501
        :type type: str
        :param submit_tool_outputs: The submit_tool_outputs of this RunObjectRequiredAction.  # noqa: E501
        :type submit_tool_outputs: RunObjectRequiredActionSubmitToolOutputs
        """
        self.openapi_types = {
            'type': str,
            'submit_tool_outputs': RunObjectRequiredActionSubmitToolOutputs
        }

        self.attribute_map = {
            'type': 'type',
            'submit_tool_outputs': 'submit_tool_outputs'
        }

        self._type = type
        self._submit_tool_outputs = submit_tool_outputs

    @classmethod
    def from_dict(cls, dikt) -> 'RunObjectRequiredAction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunObject_required_action of this RunObjectRequiredAction.  # noqa: E501
        :rtype: RunObjectRequiredAction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this RunObjectRequiredAction.

        For now, this is always `submit_tool_outputs`.  # noqa: E501

        :return: The type of this RunObjectRequiredAction.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this RunObjectRequiredAction.

        For now, this is always `submit_tool_outputs`.  # noqa: E501

        :param type: The type of this RunObjectRequiredAction.
        :type type: str
        """
        allowed_values = ["submit_tool_outputs"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def submit_tool_outputs(self) -> RunObjectRequiredActionSubmitToolOutputs:
        """Gets the submit_tool_outputs of this RunObjectRequiredAction.


        :return: The submit_tool_outputs of this RunObjectRequiredAction.
        :rtype: RunObjectRequiredActionSubmitToolOutputs
        """
        return self._submit_tool_outputs

    @submit_tool_outputs.setter
    def submit_tool_outputs(self, submit_tool_outputs: RunObjectRequiredActionSubmitToolOutputs):
        """Sets the submit_tool_outputs of this RunObjectRequiredAction.


        :param submit_tool_outputs: The submit_tool_outputs of this RunObjectRequiredAction.
        :type submit_tool_outputs: RunObjectRequiredActionSubmitToolOutputs
        """
        if submit_tool_outputs is None:
            raise ValueError("Invalid value for `submit_tool_outputs`, must not be `None`")  # noqa: E501

        self._submit_tool_outputs = submit_tool_outputs
