from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model


class RunStepDetailsToolCallsCodeOutputImageObjectImage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, file_id=None):  # noqa: E501
        """RunStepDetailsToolCallsCodeOutputImageObjectImage - a model defined in OpenAPI

        :param file_id: The file_id of this RunStepDetailsToolCallsCodeOutputImageObjectImage.  # noqa: E501
        :type file_id: str
        """
        self.openapi_types = {
            'file_id': str
        }

        self.attribute_map = {
            'file_id': 'file_id'
        }

        self._file_id = file_id

    @classmethod
    def from_dict(cls, dikt) -> 'RunStepDetailsToolCallsCodeOutputImageObjectImage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunStepDetailsToolCallsCodeOutputImageObject_image of this RunStepDetailsToolCallsCodeOutputImageObjectImage.  # noqa: E501
        :rtype: RunStepDetailsToolCallsCodeOutputImageObjectImage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_id(self) -> str:
        """Gets the file_id of this RunStepDetailsToolCallsCodeOutputImageObjectImage.

        The [file](/docs/api-reference/files) ID of the image.  # noqa: E501

        :return: The file_id of this RunStepDetailsToolCallsCodeOutputImageObjectImage.
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id: str):
        """Sets the file_id of this RunStepDetailsToolCallsCodeOutputImageObjectImage.

        The [file](/docs/api-reference/files) ID of the image.  # noqa: E501

        :param file_id: The file_id of this RunStepDetailsToolCallsCodeOutputImageObjectImage.
        :type file_id: str
        """
        if file_id is None:
            raise ValueError("Invalid value for `file_id`, must not be `None`")  # noqa: E501

        self._file_id = file_id
