from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model


class RunToolCallObjectFunction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, arguments=None):  # noqa: E501
        """RunToolCallObjectFunction - a model defined in OpenAPI

        :param name: The name of this RunToolCallObjectFunction.  # noqa: E501
        :type name: str
        :param arguments: The arguments of this RunToolCallObjectFunction.  # noqa: E501
        :type arguments: str
        """
        self.openapi_types = {
            'name': str,
            'arguments': str
        }

        self.attribute_map = {
            'name': 'name',
            'arguments': 'arguments'
        }

        self._name = name
        self._arguments = arguments

    @classmethod
    def from_dict(cls, dikt) -> 'RunToolCallObjectFunction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunToolCallObject_function of this RunToolCallObjectFunction.  # noqa: E501
        :rtype: RunToolCallObjectFunction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this RunToolCallObjectFunction.

        The name of the function.  # noqa: E501

        :return: The name of this RunToolCallObjectFunction.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this RunToolCallObjectFunction.

        The name of the function.  # noqa: E501

        :param name: The name of this RunToolCallObjectFunction.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def arguments(self) -> str:
        """Gets the arguments of this RunToolCallObjectFunction.

        The arguments that the model expects you to pass to the function.  # noqa: E501

        :return: The arguments of this RunToolCallObjectFunction.
        :rtype: str
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments: str):
        """Sets the arguments of this RunToolCallObjectFunction.

        The arguments that the model expects you to pass to the function.  # noqa: E501

        :param arguments: The arguments of this RunToolCallObjectFunction.
        :type arguments: str
        """
        if arguments is None:
            raise ValueError("Invalid value for `arguments`, must not be `None`")  # noqa: E501

        self._arguments = arguments
