from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from timestep.api.openai.v1 import util
from timestep.api.openai.v1.models.base_model import Model
from timestep.api.openai.v1.models.static_chunking_strategy_static import \
    StaticChunkingStrategyStatic  # noqa: E501


class StaticChunkingStrategy(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, static=None):  # noqa: E501
        """StaticChunkingStrategy - a model defined in OpenAPI

        :param type: The type of this StaticChunkingStrategy.  # noqa: E501
        :type type: str
        :param static: The static of this StaticChunkingStrategy.  # noqa: E501
        :type static: StaticChunkingStrategyStatic
        """
        self.openapi_types = {
            'type': str,
            'static': StaticChunkingStrategyStatic
        }

        self.attribute_map = {
            'type': 'type',
            'static': 'static'
        }

        self._type = type
        self._static = static

    @classmethod
    def from_dict(cls, dikt) -> 'StaticChunkingStrategy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Static_Chunking_Strategy of this StaticChunkingStrategy.  # noqa: E501
        :rtype: StaticChunkingStrategy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this StaticChunkingStrategy.

        Always `static`.  # noqa: E501

        :return: The type of this StaticChunkingStrategy.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this StaticChunkingStrategy.

        Always `static`.  # noqa: E501

        :param type: The type of this StaticChunkingStrategy.
        :type type: str
        """
        allowed_values = ["static"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def static(self) -> StaticChunkingStrategyStatic:
        """Gets the static of this StaticChunkingStrategy.


        :return: The static of this StaticChunkingStrategy.
        :rtype: StaticChunkingStrategyStatic
        """
        return self._static

    @static.setter
    def static(self, static: StaticChunkingStrategyStatic):
        """Sets the static of this StaticChunkingStrategy.


        :param static: The static of this StaticChunkingStrategy.
        :type static: StaticChunkingStrategyStatic
        """
        if static is None:
            raise ValueError("Invalid value for `static`, must not be `None`")  # noqa: E501

        self._static = static
