load('ext://uibutton', 'cmd_button')

port_forward_local_resource_name = 'port-forward kubeapps 8484:80'

local_resource(
    port_forward_local_resource_name,
    auto_init=False,
    labels=['ops'],
    links=['https://localhost:8484'],
    serve_cmd="kubectl port-forward -n kubeapps svc/kubeapps 8484:80",
    serve_dir='../../../../../../',
)
