#!/usr/bin/env sh
set -x # echo on

docker run \
 --env-file .env \
 --env CLOUD_INSTANCE_PROVIDER=${CLOUD_INSTANCE_PROVIDER} \
 --env DO_TOKEN=${DO_TOKEN} \
 --env DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD} \
 --env HTPASSWD=${HTPASSWD} \
 --env KUBECONFIG=${KUBECONFIG} \
 --env KUBECONTEXT=${KUBECONTEXT} \
 --env POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD} \
 --env PRIMARY_DOMAIN_NAME=${PRIMARY_DOMAIN_NAME} \
 --env SSH_PRIVATE_KEY='${SSH_PRIVATE_KEY}' \
 --env TF_API_TOKEN=${TF_API_TOKEN} \
 --env TF_USERNAME=${TF_USERNAME} \
 ${CI_REGISTRY_IMAGE}:latest poetry run cdktf deploy --auto-approve ${PRIMARY_DOMAIN_NAME}
